version: '2'
services:
  api-mock:
    build:
      context: ./api-mock
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  vgs-insurance:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VGS_USERNAME: "${VGS_USERNAME}"
      VGS_PASSWORD: "${VGS_PASSWORD}"
      VGS_VAULT: "${VGS_VAULT}"
      API_URL: "${API_URL}"
