job-defaults: &job-defaults
  working_directory: &working_directory
    ~/vgs-rails-insurance-sample

# Persists workspace so it can be attached in another jobs as soon as it was checked out and built
persist-workspace: &persist-workspace
  persist_to_workspace:
    root: .
    paths: "*"

attach-workspace: &attach-workspace
  attach_workspace:
    at: *working_directory
# === JOBS ===
version: 2
jobs:
  build:
    <<: *job-defaults
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - run:
          name: Build project
          command: |
            ./bin/bundle
      - <<: *persist-workspace
  build-docker:
    <<: *job-defaults
    machine:
      enabled: true
    steps:
      - checkout
      - <<: *attach-workspace
      - run:
          name: Build project
          command: |
            docker-compose build
workflows:
  version: 2
  build_and_tests:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build-docker:
          requires:
            - build
          filters:
            tags:
              only: /.*/